name: Build and Release Dotnet Lambda Function to S3

on:
    workflow_call:
        inputs:
            lambda_function_name:
                required: true
                type: string
            project_path:
                required: true
                type: string
        secrets:
            BUCKET_LOCATION:
                description: s3 uri for the bucket
                required: true
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true

jobs:
    dotnet_api_build:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repository
              uses: actions/checkout@v3
            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 6.0.x
            - name: Restoring dotnet packaging
              run: |
                cd $GITHUB_WORKSPACE/${{inputs.project_path}}
                dotnet restore
            - name: Building dotnet packages
              run: |
                cd $GITHUB_WORKSPACE/${{inputs.project_path}}
                dotnet tool install -g Amazon.Lambda.Tools
                export PATH="$PATH:/home/runner/.dotnet/tools"
                export DOTNET_ROOT=/home/runner/.dotnet
                config="Debug"
                dotnet build --configuration $config
                file "build.zip"
                dotnet lambda package "build.zip" -c $config
            - name: Uploading artifacts
              uses: actions/upload-artifact@v3
              with:
                name: build
                path: ${{inputs.project_path}}/build.zip
                if-no-files-found: error
    unit-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Cloning repository
            uses: actions/checkout@v3
          - name: Setup dotnet
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 6.0.x
          - name: Restoring projects
            run: dotnet restore
          - name: Building projects
            run: dotnet build --configuration Debug --no-restore
          - name: running unit tests
            run: dotnet test
        needs:
          - dotnet_api_build
    Release-To-Dev:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@v3
            name: Download build artifacts
            with:
              name: build
              path: .
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1
          - name: Upload build to S3
            run: aws s3 cp build.zip $BUCKET_LOCATION/${{github.sha}}/
            env: 
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              BUCKET_LOCATION: ${{secrets.BUCKET_LOCATION}}
          - name: Update lambda with new build
            run: |
              aws lambda update-function-code \
              --function-name  ${{inputs.lambda_function_name}} \
              --zip-file fileb://build.zip
            env: 
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        needs:
          - dotnet_api_build
          - unit-tests